# Generated by Django 3.2 on 2022-08-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_rename_achievement_cat_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(blank=True, through='cats.AchievementCat', to='cats.Achievement'),
        ),
    ]
